# Generated by Django 6.0.1 on 2026-01-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('accion', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SesionActiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('ultima_vez', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(default='Vendedor', max_length=20),
        ),
    ]
