# Generated by Django 6.0.1 on 2026-01-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_auditoria_sesionactiva_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(default='Admin', max_length=20),
        ),
    ]
